i18n: Gracefully handle lang not being available
To fix the following problem:

$ env GNUPGHOME=/tmp/homedir KEYSIGN_GPGME=1 /tmp/gks3/bin/python keysign/avahioffer.py f
You seem to be trying to execute this script directly which is discouraged. Try python -m instead.
Cannot set locale
Traceback (most recent call last):
  File "/tmp/gnome-keysign/keysign/i18n.py", line 23, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/tmp/gks3/lib64/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "keysign/avahioffer.py", line 41, in <module>
    from .i18n import _
  File "/tmp/gnome-keysign/keysign/i18n.py", line 41, in <module>
    _ = lang.ugettext
AttributeError: 'NullTranslations' object has no attribute 'ugettext'