Sections: Removed the custom SignUI and make logic explicit
I think gpg or monkeysign is confused in the presence of multiple secret
keys. I couldn't sign

root (DEBUG): Building cmd: 'gpg' '--command-fd' '0' '--with-
fingerprint' '--list-options' 'show-sig-subpackets,show-uid-validity
,show-unusable-uids,show-unusable-subkeys,show-keyring,show-sig-expire'
'--status-fd' '2' '--quiet' '--batch' '--fixed-list-mode' '--no-tty'
'--with-colons' '--use-agent' '--secret-keyring'
'/home/muelli/.gnupg/secring.gpg' '--homedir' '/tmp/pygpg-__ZAiw' '--
import'
root (DEBUG): Building cmd: 'gpg' '--command-fd' '0' '--with-
fingerprint' '--list-options' 'show-sig-subpackets,show-uid-validity
,show-unusable-uids,show-unusable-subkeys,show-keyring,show-sig-expire'
'--armor' '--status-fd' '2' '--quiet' '--batch' '--fixed-list-mode'
'--no-tty' '--with-colons' '--use-agent' '--list-secret-keys'
root (DEBUG): Building cmd: 'gpg' '--command-fd' '0' '--with-
fingerprint' '--list-options' 'show-sig-subpackets,show-uid-validity
,show-unusable-uids,show-unusable-subkeys,show-keyring,show-sig-expire'
'--armor' '--status-fd' '2' '--quiet' '--batch' '--fixed-list-mode'
'--no-tty' '--with-colons' '--use-agent' '--export'
'9BABCD219F122E774CE56405D914EC3442B00ECD'
root (DEBUG): Building cmd: 'gpg' '--command-fd' '0' '--with-
fingerprint' '--list-options' 'show-sig-subpackets,show-uid-validity
,show-unusable-uids,show-unusable-subkeys,show-keyring,show-sig-expire'
'--status-fd' '2' '--quiet' '--batch' '--fixed-list-mode' '--no-tty'
'--with-colons' '--use-agent' '--secret-keyring'
'/home/muelli/.gnupg/secring.gpg' '--homedir' '/tmp/pygpg-__ZAiw' '--
import'
root (DEBUG): Building cmd: 'gpg' '--command-fd' '0' '--with-
fingerprint' '--list-options' 'show-sig-subpackets,show-uid-validity
,show-unusable-uids,show-unusable-subkeys,show-keyring,show-sig-expire'
'--status-fd' '2' '--quiet' '--batch' '--fixed-list-mode' '--no-tty'
'--with-colons' '--use-agent' '--secret-keyring'
'/home/muelli/.gnupg/secring.gpg' '--homedir' '/tmp/pygpg-__ZAiw'
'--list-keys' 'FF52DA33C025B1E0B91092FC1C3419BF1BF98D6D'
root (INFO): Found keys {'FF52DA33C025B1E0B91092FC1C3419BF1BF98D6D':
<monkeysign.gpg.OpenPGPkey instance at 0x7f44757c4c68>} for fp
FF52DA33C025B1E0B91092FC1C3419BF1BF98D6D
root (DEBUG): Building cmd: 'gpg' '--command-fd' '0' '--with-
fingerprint' '--list-options' 'show-sig-subpackets,show-uid-validity
,show-unusable-uids,show-unusable-subkeys,show-keyring,show-sig-expire'
'--status-fd' '2' '--quiet' '--batch' '--fixed-list-mode' '--no-tty'
'--with-colons' '--use-agent' '--secret-keyring'
'/home/muelli/.gnupg/secring.gpg' '--homedir' '/tmp/pygpg-__ZAiw'
'--sign-key' 'Tobias Mueller <tobias.mueller2@mail.dcu.ie>'
Traceback (most recent call last):
File "/home/muelli/vcs/geysigning/Sections.py", line 425, in
sign_key_async
    ret = self.signui.tmpkeyring.sign_key(uidlist[0].uid, signall=True)
File "/usr/lib/python2.7/dist-packages/monkeysign/gpg.py", line 464,
in sign_key
    raise GpgRuntimeError(self.context.returncode, _('unable to open key
for editing: %s') % self.context.stderr.decode('utf-8'))
monkeysign.gpg.GpgRuntimeError: [Errno 0] unable to open key for
editing:

Now it works better.

This needs to be refactored though. We will probably have a "SignUI"
class then again ;-)