GtkKeyserver: Call DBusGMainLoop to make dbus work
I don't really understand why I need to do this and why I cannot do it
in the Avahi class.  Only this way seems to work though.

The error is the following:

python GtkKeyserver.py
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  import gobject._gobject
root (DEBUG): Running main with args: ['GtkKeyserver.py']
root (DEBUG): Starting main
root (DEBUG): toggled button
root (DEBUG): I am being switched on
root (INFO): Serving now
root (DEBUG): About to call <class 'Keyserver.ServeKeyThread'>
root (INFO): Starting thread <ServeKeyThread(Thread-1, initial daemon)>
root (INFO): Trying port 9001
root (INFO): Trying to add Avahi Service
Traceback (most recent call last):
  File "GtkKeyserver.py", line 43, in on_button_toggled
    self.setup_server()
  File "GtkKeyserver.py", line 56, in setup_server
    self.keyserver.start()
  File "/tmp/geysign-branches/Keyserver.py", line 92, in start
    ap.add_service()
  File "/tmp/geysign-branches/AvahiPublish.py", line 46, in add_service
    self.entry_group_state_changed)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 544, in connect_to_signal
    dbus_interface, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 369, in connect_to_signal
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 148, in add_signal_receiver
    path, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 400, in add_signal_receiver
    self._require_main_loop()
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)