tests: fix key import error
If the required key was not already in the keyring these tests failed.

The error was:
keysign.gpgmeh: DEBUG: Exported
'A2ECF6A72BCFD74F4165B389034094FB8FD495FB': b''
ValueError: No data to export for
A2ECF6A72BCFD74F4165B389034094FB8FD495FB (in None)