gtkexcepthook: Made it python3 compatible
If we import StringIO rather than BytesIO in Python2, we get the
following stacktrace:

Traceback (most recent call last):
File "keysign/gtkexcepthook.py", line 163, in _info
    sys.stderr.write(analyse_simple(exctyp, value, tb).getvalue())
File "keysign/gtkexcepthook.py", line 65, in analyse_simple
    traceback.print_exception(exctyp, value, tb, None, trace)
File "/usr/lib/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
File "/usr/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
TypeError: unicode argument expected, got 'str'

It seems that the StringIO expects unicode objects whereas BytesIO is
happy with "str"s, which are bytes in Python 2.