util: Use brackets for IPv6 addresses, only
With urllib3 newer than 1.22 it breaks:

urllib3.util.parse_url("http://[[127.1]]")
/tmp/gks3/lib/python3.6/site-packages/urllib3/util/url.py in
parse_url(url)
    399
    400     except (ValueError, AttributeError):
--> 401         return six.raise_from(LocationParseError(source_url),
None)
    402
    403     # For the sake of backwards compatibility we put empty

/tmp/gks3/lib/python3.6/site-packages/urllib3/packages/six.py in
raise_from(value, from_value)

LocationParseError: Failed to parse: http://[[127.1]]