gpgmeh: Add status CARDCTRL to ignored list
If not ignored, Keysign could crash due to CARDCTRL unexpected state.
This is a traceback of this error:
```
File "/tmp/wormhole/gnome-keysign/keysign/gpgmeh.py", line 76, edit_cb(self=<keysign.gpgmeh.GenEdit object>, status='CARDCTRL', args='4', sink=None)
            log.info("edit_cb: %r %r '%s'", status, args, sinkdata)
            data = self.generator.send((status, args)) #, sinkdata))
            log.info("edit_cb data: %r", data)
  variables: {'data': (None, []), 'self.generator.send': ('local', <built-in method send of generator object at 0x7f9a0c011e60>), 'status': ('local', 'CARDCTRL'), 'args': ('local', '4')}
  File "/tmp/wormhole/gnome-keysign/keysign/gpgmeh.py", line 143, sign_key(uid=0, sign_cmd='sign', expire=False, check=3, error_cb=None)
            else:
                raise AssertionError("Unexpected state %r %r" % (status, prompt))
  variables: {'AssertionError': ('builtin', <class 'AssertionError'>), 'status': ('local', 'CARDCTRL'), 'prompt': ('local', '4')}
AssertionError: Unexpected state 'CARDCTRL' '4'
```

CARDCTRL is used to control smartcard operations and should be safe to
ignore it.